### ISSUE TITLE
can't install format

### ISSUE THREAD

**Issue by isakgrozny** [Longwelwind/adventures#1]
When I try to install the format per the instructions, I get this error:
```
The story format at https://raw.githubusercontent.com/Longwelwind/adventures/master/dist/format.js could not be added ().
```
I'm not sure what's going on. I'm using a fresh install of the latest Twine 2 on OSX Sierra.

**Comment by Apophenia** [comment]
I am running into the same thing in Windows 8 with a fresh install of Twine 2. I was unable to install it in the web editor or in Windows 8.

I thought maybe GitHub was doing something weird like misreporting the MIME type, so I cloned format.js to my Bitbucket and tried to DL it from there, but then the error said it was already installed(?). I don't know why it would throw _that_ error, but it's another thing to add to the list that didn't fix it.

**Comment by Apophenia** [comment]
Ok, so other folks have had this issue with MIME type as well. I haven't built from the source so I can't tell for sure if that's what's going wrong with the desktop apps, but maybe.

This Twine format was also having issues with MIME type when trying to load directly from GitHub:
https://github.com/lazerwalker/twison/issues/9

The example here tried to download the format.js from GitHub pages, so I forked this repository and made it into a Pages repository (just set master as the pages source). This correctly set the MIME type. Buuuut, I still get the following error:

```The story format at http://lyndseyjane.com/adventures/dist/format.js could not be added (this story format is already installed).```

However, this doesn't seem to be true! When I look in the installed formats, it's just the default ones. No sign of Adventures. Same thing happens if I try to load from file in the Desktop version.

```The story format at file:///C:/Users/Lyndsey/Desktop/format.js could not be added (this story format is already installed).```

**Comment by Longwelwind** [comment]
I had the same problem in the beginning of the development; Twine's saved story formats can be "corrupt". Twine will believe it has a saved story format for that name (because, I believe, it is stored in the `localStorage`), but it didn't save the file associated to the story format.

I think the "safest" way to install Adventures is to download the `format.js` file, and use the local file path (`file://home/user/.../format.js` for Unix/OSX, and `C://Users/user/.../format.js` for Windows).

I'll look into it and hopefully find a way to make an URL that Twine accepts.

**Comment by Apophenia** [comment]
Hmm, still got ```The story format at C://Users/Lyndsey/Desktop/format.js could not be added (this story format is already installed).``` in the desktop Windows app even when using it without the file prefix. I also deleted the entirety of ```C:\Users\Lyndsey\AppData\Local\Twine``` in case that's where local storage was hiding, but that didn't help either.

Just for fun, I opened Chrome Dev Tools on Twinery.org and manually cleared all of the storage (localHost, cookies, etc) and still got the "already installed" error even though the request for the JavaScript went through OK and received a 200 (but only on http://twinery.org; trying to retrieve it from anywhere else gets a mixed content error over HTTPS).

I will try it on my Mac later and see if I get the same thing in the Desktop app.

**Comment by Apophenia** [comment]
Uninstalling and reinstalling Twine 2 for desktop also did not fix it, and there's nothing in %APPDATA% (`C:\Users\Lyndsey\AppData\Roaming`) to delete either.

**Comment by Longwelwind** [comment]
It seems it is a combination of two problems:
We can't simply use the Github's URL, we have to use RawGit because of the MIME type.
And, there's a bug in Twine; when a new story format is imported, Twine checks if an identical version isn't already registered via this code:
```
if (store.state.storyFormat.formats.some(current => {
	return current.version === data.version;
})) {
	reject(new Error(
		locale.say('this story format is already installed')
	));
	return;
}
```
In Twine, Paperthin is registered with the version `1.0.0` which directly collides with Adventures.

I will update Adventures with the version `1.0.1`, make a fork & a pull request for Twine and update the documentation !

**Comment by Apophenia** [comment]
Cool, I was able to install into twinery.org's web editor directly from my Github Pages fork's branch! It's working fine now. :)
