### ISSUE TITLE
character.inventory.hasItem not defined

### ISSUE THREAD

**Issue by Guitlle** [Longwelwind/adventures#5]
Hello. I've followed the directions in the documentation in order to test the example. 
Added the format in twinery.org, imported the downloaded html file and tested. However, it crashed complaining there were no function character.inventory.hasItem, so I defined it like this: 
```
character.inventory.hasItem=function(name) { 
   var res = false; 
   character.inventory.items.forEach(
      function (item) { 
         if (item && item.tag == name) 
            res = true; 
      }); 
      return res; 
}
```
I didn't check if the code in the repository defines, I just quickly tested and quickly added that function.

**Comment by Longwelwind** [comment]
It seems to work for me.

Can you check which version of Adventures you have ? (Click on Formats and check the version number in bold next to **Adventures**)

**Comment by nibreh** [comment]
Hello

I've got the same error, because I added the link to `format.js` found in [Installing section](https://longwelwind.github.io/adventures/basic-usage/installing.html) which is **v 1.0.2**

The good one (**v 1.1.0**) is

`https://cdn.rawgit.com/Longwelwind/adventures/920e100/dist/format.js`

Now it's working fine.

**Comment by Longwelwind** [comment]
Damn, thanks for the notice !
