### ISSUE TITLE
very very small question

### ISSUE THREAD

**Issue by rnnuid** [Longwelwind/adventures#8]
i love this format so so much, and it's what's inspiring me to actually sit down and learn javascript - but as a total beginner, I have one major question; is it possible to edit the colorscheme of the format from within twine (and thus not lose the really cool rpg assets via cloning) or is that something that it needs to be properly modified to do? Not that the colors in it already aren't nice, I just really would like to be able to change the 'lighting', as it were, when moving from scene to scene.

**Comment by Longwelwind** [comment]
Hi !

> i love this format so so much, and it's what's inspiring me to actually sit down and learn javascript

Good for you! Hope you'll be able to produce awesomes stories. 😃  

> I have one major question; is it possible to edit the colorscheme of the format from within twine (and thus not lose the really cool rpg assets via cloning) or is that something that it needs to be properly modified to do?

_Technically_, it is possible to modify everything via Javascript. Some things might be difficult to modify due to the way they were coded in Adventures (which is due to Twine's limitations for story formats). If you want to change the background image of the character panel (the left one), you can add this to the custom CSS of your story:

```css
#character-panel {
    background-image: url("http://url.to/another_image.png");
}
```

`#character-panel` is a class that is attributed to the left panel of the story. To see which interface elements has which classes, I suggest you to use the Chrome Debug Tool (Press `F12` while playing a story, it's the same one used in Google Chrome) and inspect the necessary elements.

For most of the modifications, CSS will suffice, for others, Javascript might be necessary.

Does that answer your question ?

**Comment by rnnuid** [comment]
Thank you very much, it sure does! And double thanks for such a prompt response.
